export const ActionTypes = {
	SET_USER_STARTED: 'SET_USER_STARTED',
	SET_USER_SUCCESS: 'SET_USER_SUCCESS',
	SET_USER_ERROR: 'SET_USER_ERROR',
};

export const DailyMacrosActionTypes = {
	SET_DAILY_MACROS_STARTED: 'SET_DAILY_MACROS_STARTED',
	SET_DAILY_MACROS_SUCCESS: 'SET_DAILY_MACROS_SUCCESS',
	SET_DAILY_MACROS_ERROR: 'SET_DAILY_MACROS_ERROR',
};

export const ReportNutritionTypes = {
	SET_REPORT_NUTRITION_STARTED: 'SET_REPORT_NUTRITION_STARTED',
	SET_REPORT_NUTRITION_SUCCESS: 'SET_REPORT_NUTRITION_SUCCESS',
	SET_REPORT_NUTRITION_ERROR: 'SET_REPORT_NUTRITION_ERROR',
	SET_REPORT_TIME_LINE: 'SET_REPORT_TIME_LINE',
};

export const WorkoutsActionTypes = {
	SET_WORKOUTS_STARTED: 'SET_WORKOUTS_STARTED',
	SET_WORKOUTS_SUCCESS: 'SET_WORKOUTS_SUCCESS',
	SET_WORKOUTS_ERROR: 'SET_WORKOUTS_ERROR',
};

export const TrainingSessionActionTypes = {
	SET_TRAINING_STARTED: 'SET_TRAINING_STARTED',
	SET_TRAINING_END: 'SET_TRAINING_END',
	SET_TRAINING_PAUSED: 'SET_TRAINING_PAUSED',
	SET_TRAINING_RESUME: 'SET_TRAINING_RESUME',
	SET_TRAINING_ERROR: 'SET_TRAINING_ERROR',
	SET_TRAINING_NEXT_EXERCISE: 'SET_TRAINING_NEXT_EXERCISE',
	SET_TRAINING_FINISH_EXERCISE: 'SET_TRAINING_FINISH_EXERCISE',
	SET_EXISTING_TRAINING_SESSION: 'SET_EXISTING_TRAINING_SESSION',
};
