export const ActionTypes = {
	SET_USER_STARTED: 'SET_USER_STARTED',
	SET_USER_SUCCESS: 'SET_USER_SUCCESS',
	SET_USER_ERROR: 'SET_USER_ERROR',
};

export const DailyMacrosActionTypes = {
	SET_DAILY_MACROS_STARTED: 'SET_DAILY_MACROS_STARTED',
	SET_DAILY_MACROS_SUCCESS: 'SET_DAILY_MACROS_SUCCESS',
	SET_DAILY_MACROS_ERROR: 'SET_DAILY_MACROS_ERROR',
};
